# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R CI/CD test #R-CMD-check

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'  # prevent md files (e.g., README.md) in any repo dir from trigering workflow
      - '**.bib'
      - '**.ya?ml'  # captures both .yml and .yaml
      - '**.png'
      - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - '**.md'
      - '**.bib'
      - '**.ya?ml'
      - '**.png'
      - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:  # also allow manual trigger, for testing purposes

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          #- {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      #GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rcmdcheck
            devtools

      - uses: r-lib/actions/check-r-package@v1

      - name: Build and validate models - USEEIOv2.0 detail model with waste disaggregation
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-411")
          useeior::printValidationResults(m)

        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2.0 industry model
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-i-GHG")
          useeior::printValidationResults(m)

        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2.0 summary model
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-s-GHG")
          useeior::printValidationResults(m)

        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2.0.1 detail model with waste disaggregation
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0.1-411")
          useeior::printValidationResults(m)

        shell: Rscript {0}

      #- name: Show testthat output
      #  if: always()  # step will run even if previous steps fail
      #  run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      #  shell: bash

      - name: Upload check results
        if: failure()  # if any of the previous steps fail, export a log
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check    
    
